<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <thead>
        <tr>
            <th class="col sku" scope="col"><?= $block->escapeHtml(__('SKU')) ?></th>
            <th class="col item" scope="col"><?= $block->escapeHtml(__('Product Name')) ?></th>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts) : ?>
        <tbody>
            <?php foreach ($_associatedProducts as $_item) : ?>
			<?php
					// Example: Show link only if parent product is in category 10 or 20
					$showLink = false;
					$targetCategoryIds = [63]; // Replace with your actual category IDs [7207, 7211];
					$categoryIds = $_product->getCategoryIds();
					if (!empty(array_intersect($categoryIds, $targetCategoryIds))) {
						$showLink = true;
					}
					?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col sku">
                    <!--<strong class="product-item-sku"><?= $block->escapeHtml($_item->getSku()) ?></strong>-->
					<strong class="product-item-sku">
					<?php if ($showLink): ?>
						<a href="<?= $block->escapeUrl($_item->getProductUrl()) ?>">
							<?= $block->escapeHtml($_item->getSku()) ?>
						</a>
					<?php else: ?>
						<?= $block->escapeHtml($_item->getSku()) ?>
					<?php endif; ?>
				</strong>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
               <!--     <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong> -->
					

					<strong class="product-item-name">
						<?php if ($showLink): ?>
							<a href="<?= $block->escapeUrl($_item->getProductUrl()) ?>">
							<!--<a href="<?= $block->escapeUrl($block->getUrl('catalog/product/view', ['id' => $_item->getId(), '_nosid' => true])) ?>">-->
								<?= $block->escapeHtml($_item->getName()) ?>
							</a>
						<?php else: ?>
							<?= $block->escapeHtml($_item->getName()) ?>
						<?php endif; ?>
					</strong>
					
                    <?php if ($block->getCanShowProductPrice($_product)) : ?>
                        <?php if ($block->getCanShowProductPrice($_item)) : ?>
                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))) : ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
        <?php else : ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="2">
                    <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
